init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - develop
build_script:
  - ps: .\build.ps1
clone_depth: 1
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off # Delegate to Cake
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/curemedia-ci/api/v2/package
  api_key:
    secure: 1bkesYor/4CY0QlpVc/b41CgLXyyZGwckMAEb+el94w7JCFRSogdXaHB5puoZdlX
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  skip_symbols: true
  api_key:
    secure: 34Og6nLOkZlS7tWzCb9mz8tuRdEsT8BQXSMi0xWIbobyfXEYZzZz2/XRWPOnxEb5
  on:
    appveyor_repo_tag: true
- provider: GitHub
  release: v$(appveyor_build_version)
  description: 'Release version $(appveyor_build_version)'
  auth_token:
    secure: 8l4FslQwLrkOFwUUIEcRKL69vymUgkVl+rfZ9NY+3VAkzogn44qsdzCiyYfMt+tx
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only

os: Visual Studio 2017